name: Python 3.8

on:
  push:
    branches:
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # install the python version needed
          
      - name: prepare python environment
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build twine
          pip install -r requirements.txt

      - name: tests
        run: python -m unittest tests.test_class_juliaset
        
      - name: build package
        run: python -m build